import type { StyleId, StylePreset } from "./types";

export const STYLES: StylePreset[] = [
  {
    id: "night-drive",
    name: "Night Drive",
    blurb: "Low four-on-the-floor, warm seventh pads, sub that sits in the kick.",
    bpm: 94,
    key: "F#",
    mode: "minor",
    swing: 0.08,
    kit: {
      kickStart: 168,
      kickEnd: 46,
      kickDecay: 0.42,
      snareTone: 186,
      snareNoise: 0.62,
      snareDecay: 0.16,
      hatDecay: 0.05,
      hatColor: 7800,
      percPitch: 310,
      clap: false,
    },
    mix: {
      reverbDecay: 1.6,
      delayBeats: 0.75,
      delayFeedback: 0.28,
      delayMix: 0.12,
      padFilter: 920,
      padMovement: 0.35,
      bassCutoff: 420,
      bassSub: 0.55,
      sidechain: 0.42,
      swing: 0.08,
      bpm: 94,
    },
  },
  {
    id: "warehouse",
    name: "Warehouse",
    blurb: "Dry kick, offbeat hats, a drone pad, and a short saw bass.",
    bpm: 126,
    key: "A",
    mode: "minor",
    swing: 0.02,
    kit: {
      kickStart: 150,
      kickEnd: 50,
      kickDecay: 0.28,
      snareTone: 210,
      snareNoise: 0.45,
      snareDecay: 0.1,
      hatDecay: 0.032,
      hatColor: 9200,
      percPitch: 420,
      clap: true,
    },
    mix: {
      reverbDecay: 0.85,
      delayBeats: 0.5,
      delayFeedback: 0.12,
      delayMix: 0.05,
      padFilter: 640,
      padMovement: 0.18,
      bassCutoff: 560,
      bassSub: 0.4,
      sidechain: 0.55,
      swing: 0.02,
      bpm: 126,
    },
  },
  {
    id: "dusk",
    name: "Dusk",
    blurb: "Sparse drums, long chords, bass that barely moves.",
    bpm: 76,
    key: "D",
    mode: "minor",
    swing: 0.12,
    kit: {
      kickStart: 140,
      kickEnd: 40,
      kickDecay: 0.55,
      snareTone: 160,
      snareNoise: 0.4,
      snareDecay: 0.22,
      hatDecay: 0.07,
      hatColor: 6200,
      percPitch: 240,
      clap: false,
    },
    mix: {
      reverbDecay: 2.4,
      delayBeats: 1,
      delayFeedback: 0.32,
      delayMix: 0.18,
      padFilter: 1100,
      padMovement: 0.48,
      bassCutoff: 280,
      bassSub: 0.7,
      sidechain: 0.22,
      swing: 0.12,
      bpm: 76,
    },
  },
  {
    id: "pulse",
    name: "Pulse",
    blurb: "Swung trip-hop pocket, dusty snare, walking bass.",
    bpm: 88,
    key: "C#",
    mode: "minor",
    swing: 0.38,
    kit: {
      kickStart: 155,
      kickEnd: 44,
      kickDecay: 0.38,
      snareTone: 198,
      snareNoise: 0.78,
      snareDecay: 0.2,
      hatDecay: 0.055,
      hatColor: 7000,
      percPitch: 280,
      clap: true,
    },
    mix: {
      reverbDecay: 1.8,
      delayBeats: 0.75,
      delayFeedback: 0.22,
      delayMix: 0.1,
      padFilter: 780,
      padMovement: 0.3,
      bassCutoff: 380,
      bassSub: 0.5,
      sidechain: 0.34,
      swing: 0.38,
      bpm: 88,
    },
  },
  {
    id: "fog",
    name: "Fog",
    blurb: "Dub space. Booming kick, delayed snare, a bassline that breathes.",
    bpm: 82,
    key: "E",
    mode: "minor",
    swing: 0.16,
    kit: {
      kickStart: 130,
      kickEnd: 38,
      kickDecay: 0.62,
      snareTone: 170,
      snareNoise: 0.7,
      snareDecay: 0.28,
      hatDecay: 0.08,
      hatColor: 5600,
      percPitch: 200,
      clap: false,
    },
    mix: {
      reverbDecay: 2.8,
      delayBeats: 0.75,
      delayFeedback: 0.46,
      delayMix: 0.28,
      padFilter: 540,
      padMovement: 0.4,
      bassCutoff: 300,
      bassSub: 0.75,
      sidechain: 0.28,
      swing: 0.16,
      bpm: 82,
    },
  },
  {
    id: "ritual",
    name: "Ritual",
    blurb: "Toms and a fifth-drone. More procession than groove.",
    bpm: 102,
    key: "G",
    mode: "minor",
    swing: 0.06,
    kit: {
      kickStart: 145,
      kickEnd: 48,
      kickDecay: 0.36,
      snareTone: 140,
      snareNoise: 0.35,
      snareDecay: 0.14,
      hatDecay: 0.04,
      hatColor: 4800,
      percPitch: 180,
      clap: false,
    },
    mix: {
      reverbDecay: 2.1,
      delayBeats: 1,
      delayFeedback: 0.2,
      delayMix: 0.08,
      padFilter: 480,
      padMovement: 0.22,
      bassCutoff: 240,
      bassSub: 0.65,
      sidechain: 0.18,
      swing: 0.06,
      bpm: 102,
    },
  },
];

export function getStyle(id: StyleId): StylePreset {
  return STYLES.find((s) => s.id === id) ?? STYLES[0]!;
}
